[global]
repo1-type=posix
repo1-path=/backup/pgbackrest
repo1-retention-full=2
repo1-retention-diff=4
repo1-retention-archive-type=full
process-max=2
start-fast=y
spool-path=/var/spool/pgbackrest
log-level-console=info

[rag-app]
pg1-path=/var/lib/postgresql/data
pg1-port=5432
pg1-user=postgres
